### ISSUE TITLE
SAM as a constructor parameter

### ISSUE THREAD

**Issue by andreoss** [victornoel/eo-envelopes#14]
It would be nice to have a `Scalar<X>`, `Supplier<X>` or `Callable<X>` as a constructor parameter of Envelope.

This will allow user to pass a anonymous lambda block to super constructor, like [here](
https://github.com/yegor256/cactoos/blob/9a1dc050f8cfe56cc0595331c1161c93bd7e0f44/src/main/java/org/cactoos/map/MapOf.java#L151)

```java
@GenerateEnvelope(factory = Scalar.class)
interface Foo { ... }
abstract class FooEnvelope implements Foo {
      protected FooEnvelope(final Scalar<Foo> factory) { 
          this(factory.value());
      }
      ...
}

**Comment by andreoss** [comment]
>     1. it's out of the scope of the responsibility of the envelope, it's more a concern for the user of the class

This implies a static method, which may be undesirable [1]. 
Anonymous `Scalar` object (or any other SAM)  can be refactored more easily to a real object. 
Lazy loading and caching can be achieved with that [2] (may be not considered part of envelope, but will require a second envelope anyway) 
 
>     2. I believe the example you link to is a bad example of envelope coming from incorrect implementations of envelopes in cactoos that were taking scalar, this should not normally happen, see [yegor256/cactoos#1384](https://github.com/yegor256/cactoos/issues/1384)

I see that in this case, it's indeed unnecessary. I used it as the example, because it has control structure (for-loop) inside. Having if/else, loops and exception handling inside helps , otherwise a dedicated decorator should be written for each of this control structures. 
For example, this anonymous building object
```
final class FooFile extends FooEnvelope {
    public FooFile(final Path file) {
        super(() -> { // calls FooTemplate(Scalar<Foo>)
                final Data result;
                if (file.endsWith(".json")) {
                    result = new FooJson(file);
                } else if (file.endsWith(".yaml")) {
                    result = new FooYaml(file);
                } else if (file.endsWith(".properties")) {
                    result = new FooProperties(file);
                } else {
                    throw new UnsupportedOperationException(String.format("%s is unsupported", file));
                }
                return result;
            }
        );
    }
}
```
Can latter be refactored to
```
final class FooFile extends FooTemplate {
    public FooFile(final Path file) {
        super(// calls FooTemplate(Scalar<Foo>)
            new Conditional<>(
                Map.of(
                    () -> file.endsWith(".json"), () -> new FooJson(file),
                    () -> file.endsWith(".yaml"), () -> new FooYaml(file),
                    () -> file.endsWith(".properies"), () -> new FooProperties(file)
                )
            ) 
        );
    }
}
```
`Conditinal` here is `Scalar` and can be reused
Without building object, `Foo` must have its own `Conditional`, which is not reusable
```
final class FooFile extends FooTemplate {
    public FooFile(final Path file) {
        super(// calls FooTemplate(Foo)
            new FooConditional(
                Map.of(
                    () -> file.endsWith(".json"), new FooJson(file),
                    () -> file.endsWith(".yaml"), new FooYaml(file),
                    () -> file.endsWith(".properies"), new FooProperties(file)
                )
            ) 
        );
    }
}
```



 

[1]: https://www.yegor256.com/2017/02/07/private-method-is-new-class.html
[2]: https://www.yegor256.com/2017/10/17/lazy-loading-caching-sticky-cactoos.html

**Comment by victornoel** [comment]
@andreoss if the objective is *just* to be able to write the example above, I think we will live with private static methods without problem. It is important to follow extreme precepts when it has important impact. Here clearly it is not the case: you say a private static method should be transformed to an object? But here it is exactly what the object is, it's not some part of an algorithm that could be reused or tested independently: it is the whole purpose of the class already.

Let's not forget that  Java is not perfect and thus we have to adapt to this imperfection: here all the examples are simply implementation details, they are not concerned with architecture or design or decomposition in objects, so it's not worth applying design and decomposition precepts for them IMHO.

That being said, while we discussed in the telegram chat, I understood you had actual use case where using a static private method wasn't possible because of some behavioural concerns (laziness, caching, etc). Those could be acceptable reason to modify eo-envelopes: let's focus on those use case to decide if we want to add this new feature. Could you maybe give an example of that?

**Comment by andreoss** [comment]
I concur with that static method avoidance is unnecessary. 
The OO perfection is not the point here, anonymous lambda block seems to be preferable for me though. 

>I understood you had actual use case where using a static private method wasn't possible because of some behavioural concerns (laziness, caching, etc).
The deferred initialization is the use case here. The constructor described here is a precursor for that. 

Here is how it can be done with `Sticky` (`Memoized` here). 
```
@LazyEnvelope(factory = Factory.class, container=Memoized.class)
interface Foo {...}
abstract class FooTemplate implements Foo {
    private final Factory<Foo> factory;
    protected FooTemplate(Factory<Foo> factory) {
        this.factory = new Memoized(factory);
    }
    ...
    // Foo created when any of methods called
}
final class FooValid extends FooTemplate {
    public FooValid(final Rules rules, final Foo foo) {
        super(() -> {
                    if (rules.match(foo)) { return foo; }
                    return new FooNull(rules.describeMismatch(foo));
                }
            );
    }
}
```

And as we discussed the pitfalls of naive `Sticky` implementation (more here: https://www.pragmaticobjects.com/chapters/012_caching_for_objects.html)
Here is alternative with extra `Memory` dependency used as a storage
```
@LazyEnvelope(factory = Factory.class, storage=Memory.class)
interface Foo {...}
abstract class FooTemplate {
    private final Factory<Foo> factory;
    protected FooTemplate(Memory memory, Factory<Foo> factory) {
        this.factory = memory.cache(factory);
    }
    ...
}
final class FooValid extends FooTemplate {
    public FooValid(final Memory, final Rules rules, final Foo foo) {
        super(memory, () -> {
                    if (rules.match(foo)) { return foo; }
                    return new FooNull(rules.describeMismatch(foo));
                }
            );
    }
}

**Comment by victornoel** [comment]
@andreoss honestly, this seems a bit complex and out of scope of eo-envelopes: if we start to introduce factory-based envelope, then as you perfectly demonstrated, then there will next be the need for `Memory` based envelopes, etc, etc, and it will become a huge complex thing to maintain and covering a different set of requirement than originally.

So I don't feel comfortable to adding all of that, this seems to cover a different problem that could be solved by another tool IMHO.
